[package]
name = "runic-alloc"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[lib]
name = "runic"

[lints]
workspace = true

[dependencies]
runic-core = { version = "0.8.0", path = "../runic-core" }

[[bin]]
name = "abort-case"
path = "src/bin/abort_case.rs"
