[package]
name = "runic-alloc"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[lib]
name = "runic"
crate-type = ["rlib", "cdylib"]

[features]
default = []
c-abi = ["runic-core/c-abi"]

[lints]
workspace = true

[dependencies]
libc = "0.2"
runic-core = { version = "0.8.0", path = "../runic-core" }
