[package]
name = "runic-alloc"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[lib]
name = "runic"

[features]
safe = ["runic-core/safe"]

[lints]
workspace = true

[dependencies]
runic-core = { version = "0.10.0", path = "../runic-core" }

[dev-dependencies]
libc = "0.2"

[[bin]]
name = "abort-case"
path = "src/bin/abort_case.rs"
